### ISSUE TITLE
Bug: Glaze in search results does not update the icon when published

### ISSUE THREAD

**Issue by moolric** [derekphilipau/glazy#59]
To replicate

Go to your home with the list of your glazes. 
Click on one to edit it
Change it's published status
Go back using the browser controls

The publish status icon will be the same and the glaze publish status will appear to not have changed.

Refreshing the page updates it, as the published status has actually changed.

**Comment by derekphilipau** [comment]
Just pushed a fix to production.  This error also occurred when there were other changes to a recipe like: Archiving, Copying, Deleting, etc.

**Comment by moolric** [comment]
Just tested in chrome and working perfectly. Good work :)
